package JFrame;

import java.awt.Color;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.util.ArrayList;
import java.util.Scanner;
import javax.swing.JOptionPane;

public class Login extends javax.swing.JFrame {

    public Usuario cliente;    // Objeto Usuario que contiene la información del cliente
    public ArrayList<String> archivo;  // Lista que contiene las líneas del archivo de usuarios
    
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
        archivo = new ArrayList<>();
        // Carga los datos de usuarios desde el archivo "usuarios.txt"
        try {
            Scanner lector = new Scanner(new FileReader("usuarios.txt"));
            while(lector.hasNextLine()){
                archivo.add(lector.nextLine());
            }
        } catch(FileNotFoundException ex){
            System.out.println("Error FileNotFoundException");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLbanco = new javax.swing.JLabel();
        usuariolbl = new javax.swing.JLabel();
        usuario = new javax.swing.JTextField();
        lblValidacionUsuario = new javax.swing.JLabel();
        iconcandado = new javax.swing.JLabel();
        passwordtext = new javax.swing.JLabel();
        pintfiel = new javax.swing.JPasswordField();
        lblValidacionPassword = new javax.swing.JLabel();
        ingresarbutton = new javax.swing.JButton();
        salirbut = new javax.swing.JButton();
        Registrobutton = new javax.swing.JButton();
        lblfotousuario = new javax.swing.JLabel();
        backgroundlogin = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLbanco.setFont(new java.awt.Font("Segoe UI Black", 3, 24)); // NOI18N
        jLbanco.setForeground(new java.awt.Color(204, 204, 204));
        jLbanco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lOGOA.png"))); // NOI18N
        jLbanco.setText("BANCO NACIONAL");
        jPanel2.add(jLbanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 430, 160));

        usuariolbl.setForeground(new java.awt.Color(73, 80, 87));
        usuariolbl.setText("USUARIO");
        jPanel2.add(usuariolbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, -1, -1));

        usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                usuarioMousePressed(evt);
            }
        });
        usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioActionPerformed(evt);
            }
        });
        jPanel2.add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 340, 30));

        lblValidacionUsuario.setForeground(new java.awt.Color(73, 80, 87));
        jPanel2.add(lblValidacionUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 210, 10));

        iconcandado.setBackground(new java.awt.Color(255, 255, 255));
        iconcandado.setForeground(new java.awt.Color(255, 255, 255));
        iconcandado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Lock.png"))); // NOI18N
        jPanel2.add(iconcandado, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, -1, 20));

        passwordtext.setForeground(new java.awt.Color(73, 80, 87));
        passwordtext.setText("CONTRASEÑA");
        jPanel2.add(passwordtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        pintfiel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pintfielMousePressed(evt);
            }
        });
        jPanel2.add(pintfiel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 340, 30));

        lblValidacionPassword.setForeground(new java.awt.Color(73, 80, 87));
        jPanel2.add(lblValidacionPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 230, 20));

        ingresarbutton.setBackground(new java.awt.Color(0, 51, 204));
        ingresarbutton.setForeground(new java.awt.Color(255, 255, 255));
        ingresarbutton.setText("Ingresar");
        ingresarbutton.setBorder(null);
        ingresarbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ingresarbuttonMouseClicked(evt);
            }
        });
        jPanel2.add(ingresarbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, 220, 30));

        salirbut.setBackground(new java.awt.Color(204, 0, 0));
        salirbut.setForeground(new java.awt.Color(255, 255, 255));
        salirbut.setText("Salir");
        salirbut.setBorder(null);
        salirbut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salirbutMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                salirbutMousePressed(evt);
            }
        });
        salirbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirbutActionPerformed(evt);
            }
        });
        jPanel2.add(salirbut, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 440, 220, 30));

        Registrobutton.setForeground(new java.awt.Color(116, 120, 141));
        Registrobutton.setText("¿No tienes una cuenta? Regitrate aquí");
        Registrobutton.setBorder(null);
        Registrobutton.setBorderPainted(false);
        Registrobutton.setContentAreaFilled(false);
        Registrobutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                RegistrobuttonMousePressed(evt);
            }
        });
        Registrobutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrobuttonActionPerformed(evt);
            }
        });
        jPanel2.add(Registrobutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 480, 210, 20));

        lblfotousuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/perfilorig.png"))); // NOI18N
        jPanel2.add(lblfotousuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 70, 70));

        backgroundlogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Card_Content.png"))); // NOI18N
        backgroundlogin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(backgroundlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 450, 360));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 115, 450, 520));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/t5yiz5tn.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 800));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioActionPerformed

    private void RegistrobuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrobuttonActionPerformed
    }//GEN-LAST:event_RegistrobuttonActionPerformed

    private void ingresarbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresarbuttonMouseClicked
        // Captura de los datos de usuario y contraseña
        String username=usuario.getText();
        String password=new String(pintfiel.getPassword());
        int contador=0; //Número de fila donde se encuentra el registro
        boolean usuarioNoVacio=false;
        boolean passwordNoVacio=false;
        boolean validacion=false;
        
        // Validación de campos de entrada
        if(usuario.getText().equals("Ingrese su nombre de usuario")||
                usuario.getText().isEmpty()){
            lblValidacionUsuario.setText("* Campo obligatorio");
        } else{
            lblValidacionUsuario.setText("");
            usuarioNoVacio=true;
              
        }
        
        if(password.equals("**********")||password.isEmpty()){
            lblValidacionPassword.setText("* Campo obligatorio");
        } else{
            lblValidacionPassword.setText("");
            passwordNoVacio=true;
                
            }
        // Validación de credenciales
        if(passwordNoVacio&&usuarioNoVacio){
            for(String fila:archivo) {
                String filaDeDatos[]=fila.split(";");
                if(filaDeDatos.length>2){
                    String nombreUsuario=filaDeDatos[0];
                    String passwordUsuario=filaDeDatos[1];
                    if(nombreUsuario.equals(username)&&passwordUsuario.equals(password)){
                        validacion=true;
                        break;
                    }
                }
                contador++;
            }
            if(validacion){
                String datosUsuario=archivo.get(contador);
                String splitDatosUsuario[]=datosUsuario.split(";");
                String nombreCompleto=splitDatosUsuario[2];
                ArrayList<String> cuentas=new ArrayList<>();
                ArrayList<String> tipoCuentas=new ArrayList<>();
                ArrayList<Float> saldos=new ArrayList<>();
                ArrayList<String> movimientos=new ArrayList<>();
                ArrayList<String> monedas=new ArrayList<>();
                
                // Procesa los datos del usuario
                for(int i=3;i<splitDatosUsuario.length;i+=4){
                   if(i< splitDatosUsuario.length){
                       cuentas.add(splitDatosUsuario[i]);
                   }
                    if(i + 1 <splitDatosUsuario.length){
                       tipoCuentas.add(splitDatosUsuario[i+1]);
                   }
                     if(i+2<splitDatosUsuario.length){
                       saldos.add(Float.parseFloat(splitDatosUsuario[i+2]));
                   }
                    if(i+3<splitDatosUsuario.length){
                      monedas.add(splitDatosUsuario[i+3]);
                   }
                }
                 // Crea un nuevo objeto Usuario
                cliente = new Usuario(contador,username, password, nombreCompleto,
                        cuentas,tipoCuentas, saldos,movimientos, monedas);
                MenuPrincipal menuPrincipal=new MenuPrincipal(cliente);
                menuPrincipal.setVisible(true);
                dispose();
                }
            else{
                JOptionPane.showMessageDialog(null, "Usuario no encontrado\n"
                        + "Verifique usuario y contraseña", 
                        "Error", JOptionPane.WARNING_MESSAGE);
            }
        }      
    }//GEN-LAST:event_ingresarbuttonMouseClicked

    private void salirbutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirbutMouseClicked
     
    }//GEN-LAST:event_salirbutMouseClicked

    private void usuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usuarioMousePressed
        // Limpia el campo de usuario cuando se presiona
        if(usuario.getText().equals("Ingrese su nombre de usuario")){
            usuario.setForeground(Color.black);
            usuario.setText("");
        }
        if(String.valueOf(pintfiel.getPassword()).isEmpty()){
            pintfiel.setForeground(Color.lightGray);
            pintfiel.setText("**********");        
        }
    }//GEN-LAST:event_usuarioMousePressed

    private void pintfielMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pintfielMousePressed
        // Limpia el campo de contraseña cuando se presiona
        if(usuario.getText().isEmpty()){
            usuario.setForeground(Color.lightGray);
            usuario.setText("Ingrese su nombre de usuario");
        }
        
        if(String.valueOf(pintfiel.getPassword()).equals("**********")){
            pintfiel.setForeground(Color.black);
            pintfiel.setText("");
        }
    }//GEN-LAST:event_pintfielMousePressed

    private void salirbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirbutActionPerformed
    }//GEN-LAST:event_salirbutActionPerformed

    private void RegistrobuttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistrobuttonMousePressed
        // Acción al presionar el botón de registro
        SIGNUP registro = new SIGNUP();
        registro.setVisible(true);
        dispose();
    }//GEN-LAST:event_RegistrobuttonMousePressed

    private void salirbutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirbutMousePressed
        // Cierra la aplicación
        System.exit(0);
    }//GEN-LAST:event_salirbutMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Registrobutton;
    private javax.swing.JLabel backgroundlogin;
    private javax.swing.JLabel iconcandado;
    private javax.swing.JButton ingresarbutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLbanco;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblValidacionPassword;
    private javax.swing.JLabel lblValidacionUsuario;
    private javax.swing.JLabel lblfotousuario;
    private javax.swing.JLabel passwordtext;
    private javax.swing.JPasswordField pintfiel;
    private javax.swing.JButton salirbut;
    private javax.swing.JTextField usuario;
    private javax.swing.JLabel usuariolbl;
    // End of variables declaration//GEN-END:variables
}
