/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JFrame;

import  java.time.LocalDate;

public class ReciboPago extends javax.swing.JFrame {

    public Usuario usuario;
   
    public ReciboPago(Usuario cliente,float valor, String numCuenta, String numTarjeta) {
        initComponents();
        this.setLocationRelativeTo(null);
        
        this.usuario=cliente;
        LocalDate fechaActual=LocalDate.now();
        lblPagoExitoso.setText("¡Pago exitoso!");
        lblTipoTransaccion.setText("Tarjeta");
        lblBeneficiario.setText("");
        lblNombre.setText("");
        lblValor.setText(String.valueOf(valor));
        lblCuenta.setText(numCuenta);
        lblTarjeta.setText(numTarjeta);
        txtFecha.setText(String.valueOf(fechaActual));
    }
    
    public ReciboPago(Usuario cliente, float valor, String numCuenta ,String numCuentaBene, String nombre){
        initComponents();
        this.setLocationRelativeTo(null);
        
        this.usuario=cliente;
        LocalDate fechaActual=LocalDate.now();
        lblPagoExitoso.setText("¡Transferencia exitosa!");
        lblTipoTransaccion.setText("Cuenta");
        lblBeneficiario.setText("Beneficiario");
        lblNombre.setText(nombre);
        lblValor.setText(String.valueOf(valor));
        lblCuenta.setText(numCuenta);
        lblTarjeta.setText(numCuentaBene);
        txtFecha.setText(String.valueOf(fechaActual));
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        iconcheck = new javax.swing.JLabel();
        lblPagoExitoso = new javax.swing.JLabel();
        txtvalor = new javax.swing.JLabel();
        lblValor = new javax.swing.JLabel();
        txtdesde = new javax.swing.JLabel();
        lblCuenta = new javax.swing.JLabel();
        txtpara = new javax.swing.JLabel();
        lblTipoTransaccion = new javax.swing.JLabel();
        lblTarjeta = new javax.swing.JLabel();
        lblBeneficiario = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnMenuPrincipal = new javax.swing.JButton();
        bntSalir = new javax.swing.JButton();
        txtFecha = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconcheck.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-accept-67.png"))); // NOI18N
        jPanel1.add(iconcheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 52, -1, 80));

        lblPagoExitoso.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        lblPagoExitoso.setForeground(new java.awt.Color(0, 51, 51));
        jPanel1.add(lblPagoExitoso, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 380, 50));

        txtvalor.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        txtvalor.setForeground(new java.awt.Color(0, 51, 51));
        txtvalor.setText("Valor");
        jPanel1.add(txtvalor, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, 35));

        lblValor.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblValor.setForeground(new java.awt.Color(102, 102, 102));
        jPanel1.add(lblValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 210, 35));

        txtdesde.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        txtdesde.setForeground(new java.awt.Color(0, 51, 51));
        txtdesde.setText("Desde");
        jPanel1.add(txtdesde, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, -1, 35));

        lblCuenta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblCuenta.setForeground(new java.awt.Color(102, 102, 102));
        jPanel1.add(lblCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 230, 35));

        txtpara.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        txtpara.setForeground(new java.awt.Color(0, 51, 51));
        txtpara.setText("Para");
        jPanel1.add(txtpara, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 60, 35));

        lblTipoTransaccion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTipoTransaccion.setForeground(new java.awt.Color(153, 153, 153));
        jPanel1.add(lblTipoTransaccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 120, 35));

        lblTarjeta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTarjeta.setForeground(new java.awt.Color(102, 102, 102));
        jPanel1.add(lblTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 220, 35));

        lblBeneficiario.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        lblBeneficiario.setForeground(new java.awt.Color(0, 51, 51));
        jPanel1.add(lblBeneficiario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, 140, 35));

        lblNombre.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(102, 102, 102));
        jPanel1.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 420, 240, 60));

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 51));
        jLabel5.setText("Fecha");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 480, 90, 35));

        btnMenuPrincipal.setBackground(new java.awt.Color(0, 51, 153));
        btnMenuPrincipal.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btnMenuPrincipal.setText("Menu Principal");
        btnMenuPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuPrincipalActionPerformed(evt);
            }
        });
        jPanel1.add(btnMenuPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 569, 180, 41));

        bntSalir.setBackground(new java.awt.Color(153, 0, 0));
        bntSalir.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        bntSalir.setText("Salir");
        bntSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntSalirActionPerformed(evt);
            }
        });
        jPanel1.add(bntSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 569, 180, 41));

        txtFecha.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtFecha.setForeground(new java.awt.Color(102, 102, 102));
        jPanel1.add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 490, 180, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuPrincipalActionPerformed
        MenuPrincipal menuPrincipal = new MenuPrincipal(this.usuario);
        menuPrincipal.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnMenuPrincipalActionPerformed

    private void bntSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_bntSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReciboPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReciboPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReciboPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReciboPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReciboPago(null,-1, null, null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntSalir;
    private javax.swing.JButton btnMenuPrincipal;
    private javax.swing.JLabel iconcheck;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBeneficiario;
    private javax.swing.JLabel lblCuenta;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPagoExitoso;
    private javax.swing.JLabel lblTarjeta;
    private javax.swing.JLabel lblTipoTransaccion;
    private javax.swing.JLabel lblValor;
    private javax.swing.JLabel txtFecha;
    private javax.swing.JLabel txtdesde;
    private javax.swing.JLabel txtpara;
    private javax.swing.JLabel txtvalor;
    // End of variables declaration//GEN-END:variables
}
