/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JFrame;

import java.util.Date;
import java.text.SimpleDateFormat;
import java.util.*;
/**
 *
 * @author zebal
 */
public class Splash extends javax.swing.JFrame implements Runnable{
    
    String hora, minutos,segundos;
    Thread hilo;

    /**
     * Creates new form Splash
     */
    public Splash() {
        initComponents();
        this.setLocationRelativeTo(null);
        Jlbldate.setText(fecha());
        hilo = new Thread(this);
        hilo.start();
        setVisible(true);
    }

    public void hora(){
        Calendar calendario = new GregorianCalendar();
        Date horaactual = new Date();
        calendario.setTime(horaactual);
        hora = calendario.get(Calendar.HOUR_OF_DAY)>9?""+calendario.get(Calendar.HOUR_OF_DAY):"0"+calendario.get(Calendar.HOUR_OF_DAY);
        minutos =calendario.get(Calendar.MINUTE)>9?""+calendario.get(Calendar.MINUTE):"0"+calendario.get(Calendar.MINUTE);
        segundos = calendario.get(Calendar.SECOND)>9?""+calendario.get(Calendar.SECOND):"0"+calendario.get(Calendar.SECOND);
    }
    
    public void run(){
        Thread current= Thread.currentThread();
        
        while(current == hilo){
            hora();
            Jlbltime.setText(hora+ ":"+minutos+":"+segundos);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLogo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jlbltelefonos = new javax.swing.JLabel();
        Jlbldate = new javax.swing.JLabel();
        Jlbltime = new javax.swing.JLabel();
        inicbut = new javax.swing.JButton();
        jlblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lOGOA.png"))); // NOI18N
        getContentPane().add(jLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 300, 130, -1));

        jLabel1.setFont(new java.awt.Font("MingLiU_HKSCS-ExtB", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("BANCO NACIONAL ATM 24H");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 470, 430, 80));

        jlbltelefonos.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jlbltelefonos.setForeground(new java.awt.Color(0, 0, 0));
        jlbltelefonos.setText("Telefonos de emergencia : 70412547-4487569");
        getContentPane().add(jlbltelefonos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 710, 420, 30));

        Jlbldate.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        Jlbldate.setForeground(new java.awt.Color(0, 0, 0));
        Jlbldate.setText("dd/MM/YYYY ");
        getContentPane().add(Jlbldate, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 750, 100, 20));

        Jlbltime.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        Jlbltime.setForeground(new java.awt.Color(0, 0, 0));
        Jlbltime.setText("00:00:00");
        getContentPane().add(Jlbltime, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 750, 60, 20));

        inicbut.setFont(new java.awt.Font("sansserif", 2, 24)); // NOI18N
        inicbut.setForeground(new java.awt.Color(0, 0, 0));
        inicbut.setText("Iniciar");
        inicbut.setBorder(null);
        inicbut.setBorderPainted(false);
        inicbut.setContentAreaFilled(false);
        inicbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inicbutActionPerformed(evt);
            }
        });
        getContentPane().add(inicbut, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 660, 250, 110));

        jlblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pexels-steve-9872814.jpg"))); // NOI18N
        getContentPane().add(jlblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void inicbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inicbutActionPerformed
        Login login = new Login();
        login.setVisible(true);
        dispose();// TODO add your handling code here:
    }//GEN-LAST:event_inicbutActionPerformed

    public static String fecha(){
        Date fecha = new Date();
        SimpleDateFormat formatofecha = new SimpleDateFormat("dd/MM/YYYY");
        return formatofecha.format(fecha);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Splash().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Jlbldate;
    private javax.swing.JLabel Jlbltime;
    private javax.swing.JButton inicbut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLogo;
    private javax.swing.JLabel jlblBackground;
    private javax.swing.JLabel jlbltelefonos;
    // End of variables declaration//GEN-END:variables
}
