/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JFrame;

import java.text.DecimalFormat;

public class TransferenciasInterbancarias extends javax.swing.JFrame {

    public Usuario cliente;
    DecimalFormat frmt = new DecimalFormat();
    
    public TransferenciasInterbancarias(Usuario cliente) {
        initComponents();
        this.setLocationRelativeTo(null);
        frmt.setMaximumFractionDigits(2);
        this.cliente = cliente;
        
         switch (cliente.getCantidadCuentas()) {
            case 1:
                cmbCuentas.addItem(String.valueOf(cliente.getCuenta(0)));//
                break;
            case 2:
                cmbCuentas.addItem(String.valueOf(cliente.getCuenta(0)));
                cmbCuentas.addItem(String.valueOf(cliente.getCuenta(1)));
                break;
            case 3:
                cmbCuentas.addItem(String.valueOf(cliente.getCuenta(0)));
                cmbCuentas.addItem(String.valueOf(cliente.getCuenta(1)));
                cmbCuentas.addItem(String.valueOf(cliente.getCuenta(2)));
                break;
            case 4:
                cmbCuentas.addItem(String.valueOf(cliente.getCuenta(0)));
                cmbCuentas.addItem(String.valueOf(cliente.getCuenta(1)));
                cmbCuentas.addItem(String.valueOf(cliente.getCuenta(2)));
                cmbCuentas.addItem(String.valueOf(cliente.getCuenta(3)));
        }
        lblValidCuenta.setText("");
        lblValidMonto.setText("");
        lblValidBanco.setText("");
        lblValidNum.setText("");
        lblValidNombre.setText("");
        lblValidCI.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLbanco = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmbCuentas = new javax.swing.JComboBox<>();
        lblValidCuenta = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblSaldo = new javax.swing.JLabel();
        txtSimboloDolar = new javax.swing.JLabel();
        lblmontoatransferir = new javax.swing.JLabel();
        txtMonto = new javax.swing.JTextField();
        lblValidMonto = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblNum = new javax.swing.JLabel();
        txtNumCuenta = new javax.swing.JTextField();
        lblValidNum = new javax.swing.JLabel();
        lblNom = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblValidNombre = new javax.swing.JLabel();
        btnContinuar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        cmbBanco = new javax.swing.JComboBox<>();
        lblValidCI = new javax.swing.JLabel();
        lblValidBanco = new javax.swing.JLabel();
        lblNom1 = new javax.swing.JLabel();
        lblNom2 = new javax.swing.JLabel();
        txtCI = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(0, 51, 102));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLbanco.setFont(new java.awt.Font("Segoe UI Black", 3, 24)); // NOI18N
        jLbanco.setForeground(new java.awt.Color(204, 204, 204));
        jLbanco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lOGOA.png"))); // NOI18N
        jLbanco.setText("BANCO NACIONAL");
        jPanel4.add(jLbanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 410, 190));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 180));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 51));
        jLabel1.setText("Transferencias Interbancarias");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 570, 50));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 590, 10));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 51));
        jLabel2.setText("Elija la cuenta");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 220, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 51));
        jLabel4.setText("Nro.Cuenta");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, -1, -1));

        cmbCuentas.setBackground(new java.awt.Color(255, 255, 255));
        cmbCuentas.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        cmbCuentas.setForeground(new java.awt.Color(0, 51, 51));
        cmbCuentas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-" }));
        cmbCuentas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cmbCuentas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbCuentasItemStateChanged(evt);
            }
        });
        jPanel2.add(cmbCuentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 350, 300, 30));
        jPanel2.add(lblValidCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, 270, 20));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 51));
        jLabel3.setText("Saldo Disponible");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 310, -1, -1));

        lblSaldo.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        lblSaldo.setForeground(new java.awt.Color(0, 51, 51));
        jPanel2.add(lblSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 350, 150, 30));

        txtSimboloDolar.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        txtSimboloDolar.setForeground(new java.awt.Color(0, 51, 51));
        jPanel2.add(txtSimboloDolar, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 350, 60, 30));

        lblmontoatransferir.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        lblmontoatransferir.setForeground(new java.awt.Color(0, 51, 51));
        lblmontoatransferir.setText("Monto a Transferir");
        jPanel2.add(lblmontoatransferir, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 410, 180, 30));

        txtMonto.setBackground(new java.awt.Color(255, 255, 255));
        txtMonto.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        txtMonto.setForeground(new java.awt.Color(0, 51, 51));
        jPanel2.add(txtMonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 440, 180, 30));
        jPanel2.add(lblValidMonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 480, 180, 20));

        jLabel9.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 51));
        jLabel9.setText("Datos del benefeciario");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, 230, 30));

        lblNum.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        lblNum.setForeground(new java.awt.Color(0, 51, 51));
        lblNum.setText("Nro. Cuenta");
        jPanel2.add(lblNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 510, 120, 30));

        txtNumCuenta.setBackground(new java.awt.Color(255, 255, 255));
        txtNumCuenta.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        txtNumCuenta.setForeground(new java.awt.Color(0, 51, 51));
        jPanel2.add(txtNumCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 540, 250, 30));
        jPanel2.add(lblValidNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 580, 250, 20));

        lblNom.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        lblNom.setForeground(new java.awt.Color(0, 51, 51));
        lblNom.setText("Nombre");
        jPanel2.add(lblNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 600, 80, 30));

        txtNombre.setBackground(new java.awt.Color(255, 255, 255));
        txtNombre.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(0, 51, 51));
        jPanel2.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 630, 250, 30));
        jPanel2.add(lblValidNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 670, 250, 20));

        btnContinuar.setBackground(new java.awt.Color(0, 51, 153));
        btnContinuar.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btnContinuar.setText("Continuar");
        btnContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarActionPerformed(evt);
            }
        });
        jPanel2.add(btnContinuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 720, 280, 50));

        btnVolver.setBackground(new java.awt.Color(153, 0, 0));
        btnVolver.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        jPanel2.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 720, 280, 50));

        cmbBanco.setBackground(new java.awt.Color(255, 255, 255));
        cmbBanco.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-" }));
        jPanel2.add(cmbBanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 540, 250, 30));
        jPanel2.add(lblValidCI, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 670, 250, 20));
        jPanel2.add(lblValidBanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 580, 250, 20));

        lblNom1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        lblNom1.setForeground(new java.awt.Color(0, 51, 51));
        lblNom1.setText("Seleccione el banco");
        jPanel2.add(lblNom1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 510, 190, 30));

        lblNom2.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        lblNom2.setForeground(new java.awt.Color(0, 51, 51));
        lblNom2.setText("Carnet Identidad");
        jPanel2.add(lblNom2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 600, 160, 30));

        txtCI.setBackground(new java.awt.Color(255, 255, 255));
        txtCI.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        txtCI.setForeground(new java.awt.Color(0, 51, 51));
        jPanel2.add(txtCI, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 630, 250, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarActionPerformed
        try{
            String CI = txtCI.getText();
            String nombre = txtNombre.getText();
            String cuentaEmisor = cliente.getCuenta(cmbCuentas.getSelectedIndex() - 1);
            int nombreBanco = cmbBanco.getSelectedIndex();
            String cuentaReceptor = txtNumCuenta.getText();
            
            boolean combCuenta = false;
            boolean montoValido = false;
            boolean combBanco = false;
            boolean numeroCuentaValido = false;
            boolean nombreValido = false;
            boolean cedulaValido = false;
            
            float montoPagado=-1; 
            if (txtMonto.getText().isEmpty()) {
                lblValidMonto.setText("*Campo obligatorio");
            } else {
                try {
                    float monto = Float.parseFloat(txtMonto.getText());
                    if (monto < 0) {
                        lblValidMonto.setText("*Introduzca una cantidad positiva");
                    } else {
                        if (monto > (cliente.getSaldo((cmbCuentas.getSelectedIndex()) - 1)) - 0.4) {
                            lblValidMonto.setText("*Saldo insuficiente");
                        } else {
                            montoValido= true;
                            lblValidMonto.setText("");
                            montoPagado = monto;
                        }
                    }
                } catch (NumberFormatException e) {
                    lblValidMonto.setText("*Cantidad no válida");
                }
            }
            
            if (cuentaReceptor.isEmpty()) {
                lblValidNum.setText("*Campo obligatorio");
            } else {
                for (int i = 0; i < cuentaReceptor.length(); i++) {
                    if (Character.isAlphabetic(cuentaReceptor.charAt(i))) {
                        numeroCuentaValido = false;
                        lblValidNum.setText("*Dato no válido");

                    } else {
                        numeroCuentaValido = true;
                        lblValidNum.setText("");
                    }
                }
            }


            if (cmbBanco.getSelectedIndex() == 0) {
                lblValidBanco.setText("*Seleccione un banco");
            } else {
                combBanco = true;
                lblValidBanco.setText("");
               
            }


            if (cmbCuentas.getSelectedIndex() == 0) {
                lblValidCuenta.setText("*Seleccione una cuenta");
            } else {
                combCuenta = true;
                lblValidCuenta.setText("");
            }

            if (nombre.isEmpty()) {
                lblValidNombre.setText("*Campo obligatorio");
            } else {
                for (int i = 0; i < nombre.length(); i++) {
                    if (Character.isDigit(nombre.charAt(i))) {
                        nombreValido = false;
                        lblValidNombre.setText("*Dato no válido");
                    } else {
                        nombreValido = true;
                        lblValidNombre.setText("");
                        
                    }
                }
            }
            if (CI.isEmpty()) {
                lblValidCI.setText("*Campo obligatorio");
            } else {
                for (int i = 0; i < CI.length(); i++) {
                    if (Character.isAlphabetic(CI.charAt(i))) {
                        cedulaValido = false;
                        lblValidCI.setText("*Dato no válido");
                    } else {
                        cedulaValido = true;
                        lblValidCI.setText("");
                    }
                }
            }

            if (montoValido && numeroCuentaValido && combCuenta && combBanco && nombreValido && cedulaValido) {
                montoPagado += 0.4;
                ConfirmacionPagos newframe = new ConfirmacionPagos(
                        this.cliente, txtNombre.getText(),cmbCuentas.getSelectedIndex()-1, montoPagado);
                newframe.setVisible(true);
                dispose();

            }

        } catch (Exception e) {                  

        }
    }//GEN-LAST:event_btnContinuarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        MenuPrincipal pantallaVolver = new MenuPrincipal(this.cliente);
        pantallaVolver.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void cmbCuentasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbCuentasItemStateChanged
        switch (cmbCuentas.getSelectedIndex()){
            case 0:
            lblSaldo.setText("0");
            txtSimboloDolar.setText("");
            break;
            case 1:
            lblSaldo.setText(String.valueOf(frmt.format(cliente.getSaldo(0))));
            String moneda = String.valueOf(cliente.getMoneda(0));
                if ("BOLIVIANOS".equals(moneda)) {
                    txtSimboloDolar.setText("Bs");
                } else if ("DOLARES".equals(moneda)) {
                    txtSimboloDolar.setText("US$");
                } else if ("EUROS".equals(moneda)) {
                    txtSimboloDolar.setText("£");
                } else {
                    txtSimboloDolar.setText("");
                }
            break;
            case 2:
            lblSaldo.setText(String.valueOf(frmt.format(cliente.getSaldo(1))));
            String moneda1 = String.valueOf(cliente.getMoneda(1));
                if ("BOLIVIANOS".equals(moneda1)) {
                    txtSimboloDolar.setText("Bs");
                } else if ("DOLARES".equals(moneda1)) {
                    txtSimboloDolar.setText("US$");
                } else if ("EUROS".equals(moneda1)) {
                    txtSimboloDolar.setText("£");
                } else {
                    txtSimboloDolar.setText("");
                }
            break;
            case 3:
            lblSaldo.setText(String.valueOf(frmt.format(cliente.getSaldo(2))));
            String moneda2 = String.valueOf(cliente.getMoneda(2));
                if ("BOLIVIANOS".equals(moneda2)) {
                    txtSimboloDolar.setText("Bs");
                } else if ("DOLARES".equals(moneda2)) {
                    txtSimboloDolar.setText("US$");
                } else if ("EUROS".equals(moneda2)) {
                    txtSimboloDolar.setText("£");
                } else {
                    txtSimboloDolar.setText("");
                }
            break;
            case 4:
            lblSaldo.setText(String.valueOf(frmt.format(cliente.getSaldo(3))));
            String moneda3 = String.valueOf(cliente.getMoneda(3));
                if ("BOLIVIANOS".equals(moneda3)) {
                    txtSimboloDolar.setText("Bs");
                } else if ("DOLARES".equals(moneda3)) {
                    txtSimboloDolar.setText("US$");
                } else if ("EUROS".equals(moneda3)) {
                    txtSimboloDolar.setText("£");
                } else {
                    txtSimboloDolar.setText("");
                }
            break;
        } 
    }//GEN-LAST:event_cmbCuentasItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransferenciasInterbancarias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransferenciasInterbancarias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransferenciasInterbancarias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransferenciasInterbancarias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TransferenciasInterbancarias(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContinuar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> cmbBanco;
    private javax.swing.JComboBox<String> cmbCuentas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLbanco;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblNom;
    private javax.swing.JLabel lblNom1;
    private javax.swing.JLabel lblNom2;
    private javax.swing.JLabel lblNum;
    private javax.swing.JLabel lblSaldo;
    private javax.swing.JLabel lblValidBanco;
    private javax.swing.JLabel lblValidCI;
    private javax.swing.JLabel lblValidCuenta;
    private javax.swing.JLabel lblValidMonto;
    private javax.swing.JLabel lblValidNombre;
    private javax.swing.JLabel lblValidNum;
    private javax.swing.JLabel lblmontoatransferir;
    private javax.swing.JTextField txtCI;
    private javax.swing.JTextField txtMonto;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumCuenta;
    private javax.swing.JLabel txtSimboloDolar;
    // End of variables declaration//GEN-END:variables
}
